### ISSUE TITLE
ENH: intelmqcli request - please implement filter for specific feeds

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#1]
At work a feature request appeared: can you please implement a command line parameter for intelmqcli so that it will only fetch data from a specific feed. For example:

```
$ intelmqcli  --feed=abuse.ch ....
```

Thank you!

**Comment by sebix** [comment]
The identifier is the "feed.name"? Should the wildcard be appended for the WHERE-clause (so 'blockl' matches 'BlockList.de' with `"feed.name" LIKE 'blockl%'`)? Should a list of feeds be accepted?

**Comment by aaronkaplan** [comment]
I just asked in the room next door :)
So what they want to have is a) the feed is identified by "feed.name" - YES b) whildcards - if you want to c) list of feeds - yes, nice to have , if you want to. But what's really important for them is an option --list-feeds which will do a `SELECT distinct("feed.name") from events;`
