### ISSUE TITLE
cli tool: need to close the RT ticket after a run

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#100]
After a complete run of the CLI tool, the main RT incident ticket still remains open.
This should be closed.
Note: need to be sure that no feedback (to the investigations) came back in the mean time. That's a bit tricky....

**Comment by sebix** [comment]
Suggestions how this can be achieved are welcome. Any ideas @otmarlendl?

**Comment by ghost** [comment]
The current approach worked fine for 4 years and in the meantime we have a much newer RT version with slightly different behavior
