### ISSUE TITLE
cli tool: minor thing: bottom text line wraps around

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#102]
``
0muit? stic, [n]ext, [s]end, show [t]able, change [r]equestor or [q]0
``

or:
``
uit? omatic, [n]ext, [s]end, show [t]able, change [r]equestor or [q]
``

At the bottom of the terminal.
Probably a wrap around issue (even though my terminal is wider).

**Comment by ghost** [comment]
Does this still happen on the new machine?

**Comment by aaronkaplan** [comment]
> On 14 Mar 2017, at 12:24, Wagner <notifications@github.com> wrote:
> 
> Does this still happen on the new machine?
> 

I'll check .

**Comment by aaronkaplan** [comment]
nope, it's fine
