### ISSUE TITLE
please make the squelcher's time interval configurable

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#121]
... in runtime.conf
Thanks!

**Comment by ghost** [comment]
You mean the default TTL? Currently it's in `squelcher.conf`: https://github.com/certat/intelmq/blob/master/intelmq/etc/squelcher.conf

**Comment by aaronkaplan** [comment]
> On 07 Mar 2017, at 10:15, Wagner <notifications@github.com> wrote:
> 
> You mean the default TTL? Currently it's in squelcher.conf: https://github.com/certat/intelmq/blob/master/intelmq/etc/squelcher.conf
> 

No, the 2 days

**Comment by ghost** [comment]
> No, the 2 days

In the PR  #103? https://github.com/certat/intelmq/pull/103/files#diff-5bba68521c9cfcb5f5b0c4f20a517c45R24

**Comment by aaronkaplan** [comment]
Yes this SQL stmt. as discussed yesterday - it would be great to have a parameter for this. 

---
Mobile
