### ISSUE TITLE
implement monitoring / perf monitoring concept

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#126]
See. docs/Monitoring.md

 - [ ] implement
 - [ ] test with ops and confirm that they can create graphs
 - [ ] go through all of the code and check if any condition exists which should/can raise an error. Identify which error message an admin /ops needs for this case. The text should be clearly understandable for ops. ("what do I need to do if I read this error in my alert check_mk?")
 - [ ] move to syslog in our setup and filter out the DEBUG log levels.

**Comment by ghost** [comment]
Regarding the individual issues listed:

- All bots and intelmqcli are in monitoring, alerts are sent via mail in case of issues
- check_mk creates graphs, also queue sizes
- during the operation of intelmq in the last years, log messages are steadily improved, also documentation. In same cases log messages directly link to documentation. our wiki has further information on some monitoring checks with clear instructions.
- We do not use DEBUG levels globally. As ops is not maintaining our instance, syslog is currently not needed and separate log files are easier to work with.

I therefore consider this fixed
