### ISSUE TITLE
re-working the contactDB lookup bot

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#139]
The contactDB lookup bot shall have the following functionality in the future:

1. given an `source.asn` (or dest.asn), do the following:
2. get the ASN from the DB. If it exists, check if it has a `use_ripe_netblocks` flag. If that exists, take the `source.ip` address and lookup the most specific matching netblock in the ripe_shadow_copy table. If that exists, use the `abuse_c` from there. See below for ripe_shadow_copy.
If that does not exist, ignore and take the abuse_c of the ASN.
3. If no `use_ripe_netblocks` flag exists in the DB, use the abuse_c of the ASN.

The ripe_shadow_copy DB / table can be created by periodically pulling in the RIPE DB and merging the data as given by example in https://github.com/Intevation/intelmq/tree/certbund-contact/intelmq/bots/experts/certbund_contact
Especially https://github.com/Intevation/intelmq/blob/certbund-contact/intelmq/bots/experts/certbund_contact/README-ripe-import.md

**Comment by ghost** [comment]
is to be replaced by the portal and intermediate steps, closing here
