### ISSUE TITLE
intelmqcli: missing a "s[k]ip this event" feature

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#27]
We should have a possibility to skip individual events ( in the detail view) or skip an entire group of events for an ASN.

Please use the [k] key for this (since it's already in muscle memory with old scripts) :)

**Comment by sebix** [comment]
Excluding single events does mean the user need to specify the events. By giving the id? E.g. `k 1323` removes event 1323 from the currently viewed data. Or by giving line numbers? Which means we have to display them.

**Comment by aaronkaplan** [comment]
> On 24 Nov 2015, at 20:04, Sebastian notifications@github.com wrote:
> 
> Excluding single events does mean the user need to specify the events. By giving the id? E.g. k 1323 removes event 1323 from the currently viewed data. Or by giving line numbers? Which means we have to display them.

Hm, good question. I guess we’d need to discuss with our handlers.
I’ll do so tomorrow.

**Comment by aaronkaplan** [comment]
discussed with handlers. Followup discussions in #52.
