### ISSUE TITLE
intelmqcli: safety net - do not easily overwrite contacts in the contactdb

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#28]
When doing a test and setting the recipient to a test email address, you are afterwards asked if you want to save this email.

```
Save recipient 'kaplan+test@example.com' for ASNs 760? [Y/n]n
```

However, if a contact for that ASN already exists, what then? Add the contact ("," separated list)? Or overwrite it?

In any case, I believe it is important to have a safety-check there.
Otherwise it's too easy to press Y by default.
And that can screw up our contactdb which we developed over many years.

**Comment by sebix** [comment]
If an entry exists, it will be updated (overwritten), that's what I've been asked to do.
Should the default be no?

**Comment by wagner-certat** [comment]
We no longer have an interactive mode.

**Comment by ghost** [comment]
this is obsolete anyway
