### ISSUE TITLE
intelmqcli: order of fields wrong

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#29]
Need to reorder the fields in the CSV attachment:
1. time.source
2. source.ip
3. source.asn
4. identifier
5. taxonomy
6. type
   rest...

**Comment by sebix** [comment]
Should this be hardcoded or put in a config file? How should the rest be ordered?

**Comment by aaronkaplan** [comment]
> On 10 Dec 2015, at 13:20, Sebastian notifications@github.com wrote:
> 
> Should this be hardcoded or put in a config file? How should the rest be ordered?

working on a branch now to rearrange this (hardcoded). Later we can extend this to a config file. Nice idea :)

**Comment by aaronkaplan** [comment]
also documented here: https://www.cert.at/services/data/data.html
