### ISSUE TITLE
intelmqcli: when too many events are shown, the text scrolls off the screen

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#36]
(sorry for the confusing subject title, I'll try to explain):

When you start intelmqcli and an ASN has many events and you go to the detailed view of that ASN, the text is hardly shown (just the first line) and then all the hundreds of event lines are shown. However, if we have many event lines, all the test will scroll by and you won't be able to see the whole picture anymore. 

Here is my proposal: also have the events text displayed via less(1).

TBD... there might be a better solution.

**Comment by sebix** [comment]
Isn't the whole message (to, subj, text, events) shown in less?

**Comment by aaronkaplan** [comment]
> On 15 Dec 2015, at 16:08, Sebastian notifications@github.com wrote:
> 
> Isn't the whole message (to, subj, text, events) shown in less?

no
I did not notice at least :)

**Comment by aaronkaplan** [comment]
need to wait until there are a lot of events in one case in order to reproduce

**Comment by wagner-certat** [comment]
We no longer have an interactive mode.

**Comment by ghost** [comment]
intelmqcli currently is querying the terminals height and strips the text to avoid text "overflow". Additionally in table mode a pager (less) is in use.

All in all, this works fine in daily use.
