### ISSUE TITLE
intelmqcli: please add info on the "feed.name" , "feed.url" fields to the investigation report

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#4]
It will help the recipient of the investigation report to know which URL (feed.name as well as feed.url) to look up in order to verify our claim.

It makes sense  to add this info IMHO.

**Comment by sebix** [comment]
`feed.name` is already included in the attachment. `feed.url` is problematic as there can be API keys, they need to be filtered out. Where and how should this happen?

it will now also be shown in the AS-overview as aggregate list.

**Comment by aaronkaplan** [comment]
You are right, I did not think about the API keys.
Hm, so concerning the url - for the intelmcli in the overview it's good enough to show the base hostname.

For public consumption of the data - that's a different story of course:

where would you then propose to put a link for the feed which is useable for public viewing (if such an URL is available). For example, in the case of abuse.ch - a lot of it is on a public web site. We can direct people to that.
Of course if a feed is private, we have no URL to send to the recipient.

**Comment by aaronkaplan** [comment]
feed.name may of course also not be named if the feeder does not want this. Use feed.code instead in this case. See #20

**Comment by sebix** [comment]
So we only display `feed.code`? Or only if it exists, and otherwise `feed.name`?
