### ISSUE TITLE
intelmqcli: when sending out time.* info, please add the time zone

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#41]
See ISO8601. Always always add the TZ.
Also important that we keep the lexicographic ordering

**Comment by sebix** [comment]
The query includes the TZ information: https://github.com/certat/intelmq/blob/master/intelmq/bin/intelmqcli#L164
We don't have an ordering yet.

**Comment by aaronkaplan** [comment]
actually, if you look at this this is a bug.

Try this:

```
eventdb=> select to_char(timestamp with time zone '2015-01-01 00:01:02+02' , 'YYYY-MM-DD"T"HH24:MI:SSTZ');
        to_char
------------------------
 2014-12-31T23:01:02CET
(1 row)
```

vs.

```
eventdb=> select to_char(timestamp with time zone '2015-01-01 00:01:02+02' at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SSTZ');
       to_char
---------------------
 2014-12-31T22:01:02
(1 row)
```

Adding the `at time zone 'UTC'` suppresses the printing of the tz info.

Also check out : http://www.postgresql.org/docs/9.1/static/datatype-datetime.html (section 8.5.1.3. Time Stamps) and especially the table in http://www.postgresql.org/docs/9.1/static/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT

I'd like to propose to get rid fo the `at time zone`, since pq should be able to do that just well.
But then the timestamps are printed in localtime. So either we set the local time (and TZ offset ) of the server/of postgresql to UTC (and run into other trouble with other software) or we find a way to properly print the +00 UTC time zone offset (and have the timestamp converted accordingly).

You can set postgresql's tz like this:
https://stackoverflow.com/questions/32423037/how-to-set-timezone-for-postgres-9-4-permanently

or we do it in the psycopg2 SELECT():
http://initd.org/psycopg/docs/usage.html#time-zones-handling

**Comment by aaronkaplan** [comment]
on second thought, removing the `at time zone 'UTC'` will not print UTC times . It will print local times, and yeah.. not pretty.

**Comment by aaronkaplan** [comment]
okay, I think the easiest solution is to do this:

```
eventdb=> select to_char("time.source" at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"+00"') from events where "time.source" is not null limit 10;
        to_char
------------------------
 2015-12-09T09:36:20+00
 2015-12-09T09:38:23+00
 2015-12-09T09:43:48+00
 2015-12-09T09:47:43+00
 2015-11-17T17:03:30+00
 2015-12-09T09:59:48+00
 2015-12-09T10:10:12+00
 2015-12-09T10:18:59+00
 2015-12-09T10:31:04+00
 2015-12-09T11:28:18+00
```

**Comment by aaronkaplan** [comment]
we found a better approach: since postgresql 9.4 you can add the "OF" (offset) to `to_char` print format strings. This solves it. Solution: upgrade requirements to postgresql 9.4 and use OF
