### ISSUE TITLE
intelmqcli: wish list needed cmd line flags

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#52]

**Comment by aaronkaplan** [comment]
The handlers would like to have the following features in intelmqcli:
- command line parameters:
  - [x] `--quiet` ...... Do not output anything, except for error messages. Useful in combination with --batch.
  - [x] `--batch` ..... send stuff in batch (defaults to "yes" to all)
  - [x] `--list-taxonomies` ..... list all known taxonomies
  - [x] `--list-types` ..... list all known types
  - [x] `--list-identifieres` ..... list all known identifiers
  - [x] `--asn=1234,5678,90123` ....... only process the given list of ASNs
  - [x] `--skip-asn=1234`    ...... skip processing of all events for asn 1234 (but process all other ones)
  - [x] `--feed=feedname`   ........ Show only incidents reported by the given feed (singular).
  - [x] `--skip-feed=feedname,feedname,...` ...... skip the list of feed names (but process all others)
  - [x] `--taxonomy=spam` ..... only process events of taxonomy=spam
  - [x] `--skip-taxonomy=spam` ..... skip processing of all spam (taxonomy field) (but process all other ones)
  - [x] `--skip-type=virut` ..... skip processing of all type=virut events (but process all other ones)
  - [x] `--type=virut` ..... only process events of type=virut
  - [x] `--skip-identifiers=foobar` ..... skip processing of all identifier=foobar events
  - [x] `--identifier=foobar` ...... only process events of identifier=foobar
- [ ] a delay feature (to be defined in more detail): the handlers would like to be able to say that all events of `type=foo` or `taxonomy=spam` or `identifier=bar` or `asn=1234` should be "delayed" - in other words the squelcher should behave as it if had been sent but we actually don't send it out via RTIR. So the effect is that nobody gets annoyed about these events, but the handlers will get reminded of them $ttl seconds later again.

**Comment by aaronkaplan** [comment]
--quiet added with #56

**Comment by aaronkaplan** [comment]
wishlist by @otmarlendl : please by default go over all taxonomies first.

```
for t in $TAXONOMIES; do
  ./intelmqcli --taxonomy=$t --quiet --batch
done
```

Shall create an RTIR incident report for each run, attach it to an RTIR incident (ticket), set the classification=$t and for each ASN send out all events (of this taxonomy value) .
See also #53

**Comment by sebix** [comment]
`--taxonomy=` implemented in 613e3f88e312680c172911698b8054c23caba8d0

**Comment by sebix** [comment]
`--asn=` implemented in  21b9e42fa3541e0cd2b9d49c4b027df21e98bd21

**Comment by sebix** [comment]
`--type` implemented in 8f9de6f

**Comment by sebix** [comment]
`--identifier` implemented in 41ac411

**Comment by sebix** [comment]
Concerning the delay feature: To represent this state, we could set sent_at to the current timestamp and leave incident and investigation id empty. Needs some minor adaptions on the queries but easily duable.

**Comment by sebix** [comment]
`--skip-*` implemented in #99

**Comment by ghost** [comment]
> Concerning the delay feature: To represent this state, we could set sent_at to the current timestamp and leave incident and investigation id empty. Needs some minor adaptions on the queries but easily duable.

@aaronkaplan What do you think about this approach?

**Comment by aaronkaplan** [comment]
sounds like a hack

**Comment by ghost** [comment]
Introduce another column?

**Comment by ghost** [comment]
A delay feature as described here has not been needed so far. But the handlers are aware of the effect when setting notify (to true/false) manually. This is in use for the webinput for example, for force sending notifications.
