### ISSUE TITLE
intelmqci: implement zip attachments

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#58]
The code is already there, but not used:

```
        if True:  # TODO: implement zip config
            attachment = csvfile
            attachment.seek(0)
            filename = 'events.csv'
        else:
            attachment = io.BytesIO()
            ziphandle = zipfile.ZipFile(attachment, mode='w')
            ziphandle.writestr('events.csv', csvfile.getvalue())
            ziphandle.close()
            attachment.seek(0)
            filename = 'events.zip'
```

Can we somehow have the zipped attachments? How about making it a cmd line option?

**Comment by sebix** [comment]
Yes, we deactivated the possibility, as this said that the switch will
be implemented via the contact database (as per-recipient format rule).

Of course I can add a commandline parameter if you want.

**Comment by aaronkaplan** [comment]
---

iPhone, iTypos, iSorry

> On 20.04.2016, at 18:46, Sebastian notifications@github.com wrote:
> 
> Yes, we deactivated the possibility, as this said that the switch will
> be implemented via the contact database (as per-recipient format rule).

Thanks. Yes true true. Better put it there.
