### ISSUE TITLE
Merge upstream?

### ISSUE THREAD

**Issue by Rafiot** [certat/intelmq#61]
Hi all,

It took me a while to realize that https://github.com/certtools/intelmq and https://github.com/certat/intelmq have diverged a bit.

Would it make sense to merge some of the patches upstream? Especially `intelmqcli`.

**Comment by aaronkaplan** [comment]
Well so far we intentionally kept the certat repo separate because it seems to be very specific to our needs (our approach to using a PostgreSQL db etc )

In general I'd like to have as little differences between the repos as possible.  Yes. 
But I am unsure on how much of the certat should be in the general repo. I guess we need user feedback on this matter. 

Best,
A.

---

Mobile

**Comment by Rafiot** [comment]
Ok, I was not sure it was intentional. The cli seems to be interesting but I'll look at it a bit more and maybe propose a PR to merge a part upstream.

**Comment by aaronkaplan** [comment]
> On 12 Jul 2016, at 14:19, Raphaël Vinot notifications@github.com wrote:
> 
> Ok, I was not sure it was intentional. The cli seems to be interesting but I'll look at it a bit more and maybe propose a PR to merge a part upstream.

cool! Thanks.
Note that it does have a lot of certat specifics there.

Best,
a.

**Comment by sebix** [comment]
This fork has all changes and additions (intelmqcli, squelcher and heartbeat) we needed to smoothly integrate intelmq into our existing setup, without changing existing processes here. But the latter is needed anyway and we want to keep the structure of intelmq and it's workflow.

Additionally: All the adaptions haven't been discussed with the community at all!

**Comment by Rafiot** [comment]
No worries, I talked with aaron earlier today about integration with RT (intelmq ->  RT) and he sent me a link to intelmqcli, which I didn't see before and I realized later that the tool was on certat fork. 

I was basically just curious.
