### ISSUE TITLE
UX: useability request: trim long columns

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#71]
Please do not make the table colums for email address and feed.name bigger than X characters. If its larger (in the CLI) than X characters, please (optically) truncate the visual display of it.

**Comment by sebix** [comment]
What should the default maximum length be? (Or not configurable?)

**Comment by aaronkaplan** [comment]
> On 13 Sep 2016, at 13:19, Sebastian notifications@github.com wrote:
> 
> What should the default maximum length be? (Or not configurable?)
> 
> I'd say check how wide the terminal is and then adjust accordingly.
> Assume a minimum window size of 80 columns. 132 is more common with larger terminals

Maybe it's possible to find a right balance.

**Comment by wagner-certat** [comment]
We no longer have an interactive mode.

**Comment by ghost** [comment]
Is this still relevant?

**Comment by aaronkaplan** [comment]
nope, let's close it
