### ISSUE TITLE
contact-lookup enricher lookup cronjob

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#78]
We need a script which goes through all events, which could be sent out but are not because no matching abuse contact could be found at the time of inserting the event into the eventdb.
Maybe a new contact was found for a specific ASN and the event can actually be delivered at the time of running this script.

However, care must be taken that we don't send out very old data. So a certain TTL (default: 1 month) needs to be enabled by default.

**Comment by otmarlendl** [comment]
This comment mixes up different tasks:
- we need a script to detect if (and what) events have not been assigned a contact address
- we need a way that a human can update the missing data
  - that can be by updating the underlying contact-DB
  - that could be manually setting the address just for this set of events
- we need a way to re-run the expert-bot to pick up the new data and re-schedule the events for mailing them out

---

The proposed default of 1 month cutoff is _way_ too long. A week is already an upper limit on usefulness, and it's much better if the default is set to 3 days.

**Comment by ghost** [comment]
We already use the data from RIPE as fallback for very long time.

Also, with the Constituency Portal in place, the whole process will change again and the `as_contacts` table will hopefully fade out soon.

As the issue does no longer exist with the fallback, I'm closing here.
